---
dist: xenial
language: python
python: 3.7
services: docker
env:
- STEP=geni VERSION=v0.9.9.2
install:
- git clone https://github.com/systemslab/popper /tmp/popper
- pip install /tmp/popper/cli
script:
- popper run --substitution _STEP=$STEP --substitution _VERSION=$VERSION -f .ci.yml
